// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace entities.Models;

public partial class Student
{
    public int StudentId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public DateOnly? DateOfBirth { get; set; }

    public char? Gender { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public DateTime? AdmissionDate { get; set; }

    public decimal? Gpa { get; set; }

    public bool? IsActive { get; set; }

    public int? CourseId { get; set; }

    public virtual Course Course { get; set; }
}